inherit_from: ~/.config/rubocop/config.yml

AllCops:
    Exclude:
    - 'test/*.rb'

# Prefer double quotes
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Specifies soft and hard limits.
Layout/LineLength:
  Severity: info
  Details: 80 soft, 120 hard
  Max: 120 # Why isn't there a way to specify the soft limit
  AutoCorrect: false
  IgnoredPatterns: ['^\s*#.+'] # Ignore comments, but try to keep them under 80 

# Allow empty line before rescue
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

# Poddl uses a Japanese charachters in examples
Style/AsciiComments:
  Enabled: false

# Move MethodLength to 20
Metrics/MethodLength:
  Max: 20
